language: java
jdk:
- oraclejdk7
- openjdk6
env:
  global:
  - secure: TO3oA+i1BRv1eTyHlf2oD9v7Mlh+ZRI2qcy6+vbKvWwKhE97eIl24TBrRnivrAYvDSCb7LQbKfYdlylIAz1j2/sm69A3mwjAxRZetekLesRszy/cgc5FDmMh9x9KgOwDfJlVm8Z1uT2UwZ/AfEGFbLFPjHAcp4jbPgdJcUr2SuY=
  - secure: DTW8kDZ42rWcsBXigza0xgTq/O+rPsAKW5u4qGKIvVQKCc73Zj8mMpIHzKRYx68lvB4XY3rFmK4PrKpa/BExjGTH47GIw1MiReFMt6Y2aKL1SYQLnz+mxH923MXu3iMySVShCbJCXuatqJLnl0vHmf+kSLux6PwM79w06Sxrz7Y=
  - secure: O9d1Y7YwS0RaHLaQHkghuxOenTMb6yvHNibZ2YWHAbCJ97A9AI4IykaI9RTRy+p2r0C04XFsH7xV2s/j8zQakXvdjlSPmC8CtK6qmyULZ+YYPnKwlLuQCZ6BwXwBimJC0HbIizzk12nIhQgYRqhQ/YzAhCWwM59iHHpfAiBxf/s=
before_install:
- export TERM=dumb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: ./gradlew integTest check Javadoc --info --stacktrace
after_success:
- .utility/initiate-publish.sh
- .utility/push-javadoc-to-gh-pages.sh
